services:
  - type: web
    name: gmail-client-api
    env: node
    plan: free
    runtime: node-18
    buildCommand: cd backend && npm install && npx prisma db push
    startCommand: cd backend && npm start
    
    envVars:
      - key: DATABASE_URL
        scope: build
      - key: GOOGLE_CLIENT_ID
      - key: GOOGLE_CLIENT_SECRET
      - key: GOOGLE_REDIRECT_URI
        value: https://gmail-client-api.onrender.com/auth/callback
      - key: JWT_SECRET
      - key: FRONTEND_URL
        value: https://gmail-client-api.onrender.com
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

databases:
  - name: gmail_client_db
    databaseName: gmail_client_db
    plan: free
    version: 15
    region: ohio
    ipAllowList: []
